sudo: false

language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

install:
  mvn -B install -U -DskipTests=true

script:
  mvn -B verify -U

cache:
  directories:
    - $HOME/.m2