sudo: false

language: java

jdk:
  - oraclejdk11

addons:
  apt:
    packages:
      - oracle-java8-installer

install:
  mvn -B install -U -DskipTests=true

script:
  mvn -B verify -U

after_script:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.m2