version: '3'
services:
  redis:
    image: "redis:3.0.6"
    ports:
      - "6379:6379"
  config-service:
    image: "alexanderlloyd/config-service:1.0"
    ports:
      - "8081:8080"
    environment:
      REDIS_HOST: "localhost"
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""